### ISSUE TITLE
libqtxdg 4.2.0 fails to build with qt 6.10.0

### ISSUE THREAD

**Issue by Biswa96** [lxqt/libqtxdg#320]
* Compiler error:

```
In file included from src/xdgiconloader/xdgiconloader.cpp:37:
src/xdgiconloader/xdgiconloader_p.h:55:10: fatal error: 'private/qicon_p.h' file not found
   55 | #include <private/qicon_p.h>
      |          ^~~~~~~~~~~~~~~~~~~
```

**Comment by Biswa96** [comment]
Thanks. That commit fixed the issue.

**Comment by tsujan** [comment]
There are similar PRs for a few other components. We should merge them too before LXQt 2.3.0.

**Comment by stefonarch** [comment]
Looks it was released yesterday: https://wiki.qt.io/Qt_6.10_Release
